version: '3'

services:
  database:
    image: postgres:15-alpine
    container_name: 'tq-db'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - tq_data:/var/lib/postgresql/data:rw

volumes:
  tq_data:
